### ISSUE TITLE
REST principles and confusing API

### ISSUE THREAD

**Issue by temsa** [Qard/GECK#1]
REST principle is using the PUT http method for creating a resource, and POST to modify the resource.

Geck just swaps this convention, should you not stick Geck to this convention in order not to provide a confusing API ?

**Comment by Qard** [comment]
I've always seen it as the other way around. http://en.wikipedia.org/wiki/Representational_State_Transfer#RESTful_web_services

**Comment by temsa** [comment]
Ok, yes, my bad, pure mistake here : "POST /resource create" I believed, reading the documentation, that "create" means "creating the resource collection" at first (which is either a "POST  /" or a "PUT  /resource" in my experience, e.g. [CouchDB API for databases](http://wiki.apache.org/couchdb/HTTP_database_API#PUT_.28Create_New_Database.29), but should be the first one I guess).

I can't believe using so much REST APIs and doing this mistake o_O

Cheers

**Comment by Qard** [comment]
Yeah, Geck is a bit weird in that it creates the resource list for you. POSTing to /resource creates a new resource IN that list. Basically it's the same as POSTing to /resource/id, except it lets the server decide the id for you.
